version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.17-bullseye
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    user: vscode
