# syntax=docker/dockerfile:1.4

# [Choice] Go version (use -bullseye variants on local arm64/Apple Silicon): 1, 1.16, 1.17, 1-bullseye, 1.16-bullseye, 1.17-bullseye, 1-buster, 1.16-buster, 1.17-buster
ARG VARIANT="1"
FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/go:0-${VARIANT}
